version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynet
  authenticationDBMigration:
    image: authmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDB
    networks:
      - mynet
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
      - 5002:5002
    networks:
      - mynet
volumes:
  dbdata:

networks:
  mynet: